version: "3.9"
services:
  number-to-words:
    build:
      context: .
    ports:
      - "5000"
    volumes:
      - .:/app
    command: >
      sh -c "gunicorn main:app --proxy-headers --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:5000 --log-level info"
  nginx:
    image: nginx:alpine
    depends_on:
      - number-to-words
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
